apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-virtual-service
  namespace: istio-system
spec:
  hosts:
  - kiali.istio-example.nl
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: kiali
        port: 
          number: 20001
    timeout: 5s
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-virtual-service
  namespace: istio-system
spec:
  hosts:
  - grafana.istio-example.nl
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: grafana
        port: 
          number: 3000
    timeout: 5s
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-virtual-service
  namespace: istio-system
spec:
  hosts:
  - prometheus.istio-example.nl
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: prometheus
        port: 
          number: 9090
    timeout: 5s
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: zipkin-virtual-service
  namespace: istio-system
spec:
  hosts:
  - zipkin.istio-example.nl
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: zipkin
        port: 
          number: 9411
    timeout: 5s
