apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: default-service
  namespace: default
spec:
  hosts:
  - example.com
  gateways:
  - gateway
  http:
  - fault:
      delay:
        fixedDelay: 5s
        percentage:
          value: 5
      abort:
        httpStatus: 500
        percentage:
          value: 5
    match:
    - uri:
        exact: /
    - uri:
        prefix: /callback
    - uri:
        prefix: /static
    - uri:
        regex: '^.*\.(ico|png|jpg|svg)$'
    route:
    - destination:
        host: default-service
        port:
          number: 80
        subset: v1
      weight: 90
    - destination:
        host: default-service
        port:
          number: 80
        subset: v2
      weight: 10
    mirror:
      host: default-service
      subset: v2
    mirrorPercentage:
      value: 100
    timeout: 5s
    retries:
      attempts: 2
      perTryTimeout: 5s
---
# DestinationRule defines policies that apply to traffic intended for a service after routing has occurred.
# These rules specify configuration for load balancing, connection pool size from the sidecar,
# and outlier detection settings to detect and evict unhealthy hosts from the load balancing pool.
# https://istio.io/latest/docs/reference/config/networking/destination-rule/
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: default-service-destination-rule
  namespace: default
spec:
  host: service
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
    connectionPool:
      tcp:
        maxConnections: 10
        connectTimeout: 30ms
        tcpKeepalive:
          probes: 9
          time: 3600s
          interval: 75s
      http:
        http1MaxPendingRequests: 1
        http2MaxRequests: 10
        maxRequestsPerConnection: 2
        idleTimeout: 3600s
        h2UpgradePolicy: UPGRADE # Upgrade http1.1 to http2
        useClientProtocol: false
    outlierDetection:
      baseEjectionTime: 2m
      consecutiveGatewayErrors: 1 # 502, 503 or 504
      interval: 1s
      maxEjectionPercent: 100
      minHealthPercent: 0
    tls:
      mode: ISTIO_MUTUAL
